# -*- coding: utf-8 -*-
"""Final_Version.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RpEu-tqnOn9m_WZvpDuF56g9emp0c9De
"""

!pip uninstall -y torch torchvision torchaudio transformers openai
!pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 transformers openai==0.28

import torch
from transformers import Blip2Processor, Blip2ForConditionalGeneration
import openai
import requests
import cv2
import numpy as np
from PIL import Image
import base64

# ✅ Load BLIP-2 Model for Image Captioning
blip_model_name = "Salesforce/blip2-opt-2.7b"

blip_processor = Blip2Processor.from_pretrained(blip_model_name, force_download=True)
blip_model = Blip2ForConditionalGeneration.from_pretrained(blip_model_name, force_download=True).to("cuda")

print("✅ BLIP-2 Model Loaded Successfully!")

from google.colab import files
from PIL import Image

# Upload an image file
uploaded = files.upload()

# Get the uploaded file name
image_path = list(uploaded.keys())[0]

# Open and display the uploaded image
image = Image.open(image_path)
image.show()

print(f"✅ Uploaded Image: {image_path}")

def resize_image(image_path, max_size=512):
    """
    Resizes image to a max dimension (512px) to reduce API request size.
    """
    img = Image.open(image_path)
    img.thumbnail((max_size, max_size))
    img.save("resized_image.jpg")  # Save the resized image
    return "resized_image.jpg"

# Resize before sending to BLIP-2
image_path = resize_image(image_path)

def generate_blip_description(image_path):
    """
    Uses BLIP-2 to describe clothing in an image.
    """
    image = Image.open(image_path).convert("RGB")
    inputs = blip_processor(images=image, return_tensors="pt").to("cuda")

    output = blip_model.generate(**inputs)
    description = blip_processor.decode(output[0], skip_special_tokens=True)

    return description

# Get clothing description
description = generate_blip_description(image_path)

print(f"📝 **Generated Clothing Description:** {description}")



import openai
openai.api_key = ""

def extract_clothing_labels(description):
    """
    Uses GPT-4 to refine BLIP's description into structured clothing labels.
    """
    prompt = f"""
    Given the following detailed clothing description:

    '{description}'

    Extract and list only the specific clothing items (e.g., "Saree", "Salwar Kameez", "Jeans", "T-shirt").
    Do not include unrelated details.
    """

    response = openai.ChatCompletion.create(
        model="gpt-4-turbo",
        messages=[{"role": "system", "content": prompt}]
    )

    return response["choices"][0]["message"]["content"]

# Extract clothing labels
clothing_labels = extract_clothing_labels(description)
print(f"👕 **Extracted Clothing Labels:** {clothing_labels}")
